set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_130s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -20
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_130s_bladerf.bin format=bin
tx start
tx wait
