set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037812_3.724780_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037351_3.723720_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036683_3.721692_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036842_3.718699_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.036660_3.717819_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.037822_3.718758_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038469_3.719418_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039174_3.720716_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.039228_3.722025_110s_bladerf.bin format=bin
tx start
tx wait
set frequency tx 1575.42M
set samplerate 2.6M
set bandwidth 2.5M
set txvga1 -17
set txvga2 0
cal lms
cal dc tx
tx config file=gps_51.038024_3.722969_110s_bladerf.bin format=bin
tx start
tx wait
